### ISSUE TITLE
some question about simple_lm_finetuning

### ISSUE THREAD

**Issue by woocoder** [allenai/commonsense-kg-completion#4]
Hello, could you tell me the details of  fine-tune code? 
I'm trying to add some nodes in the atomic node data, and I need to re-train bert embedding of the nodes.

But I got some trouble with simple_lm_finetuning.py
`RuntimeError: index out of range: Tried to access index -1 out of table with 511 rows. at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418`
with debug ,I can see that the 'lm_label_ids' variable contains "-1".

Here is my 'train_corpus', the struct is same with your 'atomic_node_names.txt' file:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/11451001/86430375-adc40b00-bd24-11ea-9a26-5c30f2379685.png">

And if we change the train_corpus to your 'atomic_node_names.txt' file, the error still appears.

My transformers lib is version 2.2.0
Is there some thing wrong?

**Comment by chaitanyamalaviya** [comment]
Hi! The error was due to an earlier incompatible version of the transformers repo and it should be fixed with the latest commit on this repo. FYI, I'm using transformers version 3.0.1.

**Comment by woocoder** [comment]
> Hi! The error was due to an earlier incompatible version of the transformers repo and it should be fixed with the latest commit on this repo. FYI, I'm using transformers version 3.0.1.

Hi, Thank you for your reply. But it's not work for me.

I'm change the transformers version to 3.0.1, but still get error message.

here is my example print message:
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/11451001/86589230-dca9dd80-bfbf-11ea-86c9-6dc7f7bae725.png">

here is my traceback:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/11451001/86589277-f21f0780-bfbf-11ea-9439-ab337f9788ec.png">

It looks like the lm_label_ids cannot be '-1'.

**Comment by woocoder** [comment]
> Hi! The error was due to an earlier incompatible version of the transformers repo and it should be fixed with the latest commit on this repo. FYI, I'm using transformers version 3.0.1.

Hi, I think I found the answer.

the function parameters was not map to the right position.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/11451001/86592321-d0c11a00-bfc5-11ea-97cd-6d49ecfa94ed.png">

Here is BertForMaskedLM 'forward' function, but I don't know the 'is_next'  mean. How to handle this?
<img width="320" alt="image" src="https://user-images.githubusercontent.com/11451001/86592540-3f9e7300-bfc6-11ea-8790-a3f03aae9e03.png">

thank you :)

**Comment by chaitanyamalaviya** [comment]
If you were to pull from the repo again, this issue should be resolved already. 
The model class used here is `BertForPreTraining` and the keyword argument `next_sentence_label` should be equal to `is_next`.

**Comment by woocoder** [comment]
> If you were to pull from the repo again, this issue should be resolved already.
> The model class used here is `BertForPreTraining` and the keyword argument `next_sentence_label` should be equal to `is_next`.

Yes! the problem has been solved.

And I get the result like this

<img width="793" alt="image" src="https://user-images.githubusercontent.com/11451001/86779809-8ce61780-c08e-11ea-81ff-005240031120.png">

But compare with the 'bert_model_embeddings/nodes-lm-atomic' folder, there is not the 'atomic_bert_embeddings.pt'.

Do I need use for each the atomic_nodes_names to get the bert embedding?

Just like this?

<img width="670" alt="image" src="https://user-images.githubusercontent.com/11451001/86785986-fa497680-c095-11ea-90cc-32221ee6ece5.png">

**Comment by chaitanyamalaviya** [comment]
Yes, that's right. The `atomic_bert_embeddings.pt` are actually generated and saved to disk when you run the KB completion script (in [this method](https://github.com/allenai/commonsense-kg-completion/blob/master/src/bert_feature_extractor.py#L184)).

**Comment by woocoder** [comment]
> Yes, that's right. The `atomic_bert_embeddings.pt` are actually generated and saved to disk when you run the KB completion script (in [this method](https://github.com/allenai/commonsense-kg-completion/blob/master/src/bert_feature_extractor.py#L184)).

Thank you for your reply.

Well, I can understand the model need to load the pretrained lm 'lm_pytorch_model' then calculate the ber_embedding, but I got some new question.

1. This code need to use the network to get node_list [link](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/bert_feature_extractor.py#L233), but in [here](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/model.py#L176) is not set the network, so I changed like this :
<img width="736" alt="image" src="https://user-images.githubusercontent.com/11451001/86880081-c36b7300-c11e-11ea-9fcd-fed9c4a1b327.png">


2, The original 'lm_pytorch_model.bin' file need to load from 'torch.load('lm_pytorch_model.bin')' with 'pytorch-pretrained-bert' , so I install the dependence (version is 0.6.2)

3. when I run the code, [here](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/bert_feature_extractor.py#L258) function will throw an error (error point in apex package).

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/11451001/86880450-4d1b4080-c11f-11ea-8449-03a555199bf4.png">

4. when I uninstall the apex package, I got the error like this.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/11451001/86881596-4097e780-c121-11ea-85fc-e1f1b11bd2c9.png">
<img width="976" alt="image" src="https://user-images.githubusercontent.com/11451001/86881733-8a80cd80-c121-11ea-98d3-0e919e581d4b.png">


 It seems like it's a 'pytorch-pretrained-bert' package bug.

How should I fix this.

Thank you very much!

**Comment by woocoder** [comment]
> 
> 
> > Yes, that's right. The `atomic_bert_embeddings.pt` are actually generated and saved to disk when you run the KB completion script (in [this method](https://github.com/allenai/commonsense-kg-completion/blob/master/src/bert_feature_extractor.py#L184)).
> 
> Thank you for your reply.
> 
> Well, I can understand the model need to load the pretrained lm 'lm_pytorch_model' then calculate the ber_embedding, but I got some new question.
> 
>     1. This code need to use the network to get node_list [link](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/bert_feature_extractor.py#L233), but in [here](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/model.py#L176) is not set the network, so I changed like this :
> 
> 
> <img alt="image" width="736" src="https://user-images.githubusercontent.com/11451001/86880081-c36b7300-c11e-11ea-9fcd-fed9c4a1b327.png">
> 
> 2, The original 'lm_pytorch_model.bin' file need to load from 'torch.load('lm_pytorch_model.bin')' with 'pytorch-pretrained-bert' , so I install the dependence (version is 0.6.2)
> 
>     1. when I run the code, [here](https://github.com/allenai/commonsense-kg-completion/blob/d3ead4d9a9056bef007c65738febea77deb88757/src/bert_feature_extractor.py#L258) function will throw an error (error point in apex package).
> 
> 
> <img alt="image" width="1024" src="https://user-images.githubusercontent.com/11451001/86880450-4d1b4080-c11f-11ea-8449-03a555199bf4.png">
> 
>     1. when I uninstall the apex package, I got the error like this.
> 
> 
> <img alt="image" width="1008" src="https://user-images.githubusercontent.com/11451001/86881596-4097e780-c121-11ea-85fc-e1f1b11bd2c9.png">
> 
> <img alt="image" width="976" src="https://user-images.githubusercontent.com/11451001/86881733-8a80cd80-c121-11ea-98d3-0e919e581d4b.png">
> 
> It seems like it's a 'pytorch-pretrained-bert' package bug.
> 
> How should I fix this.
> 
> Thank you very much!

Oh, I see.

The pytorch-pretrained-bert version is 0.3.0, It works now.

P.S. Suggest to add the version in the requirements.txt.
